### ISSUE TITLE
Review for Back-End position

### ISSUE THREAD

**Issue by nenadpejic** [nikicivan/basic-shop-API#1]
Hello @nikicivan ,

Thank you for your submission.
Below this you can find my review. In short, the project is very well done.
I will send my feedback to HR.

Cheers,
Nenad

```
Review for: nikicivan
Completed on: 19.03.2021
Assignment: https://github.com/polazak/assignments/blob/main/basic-shop.job-interview-assignment.md


From assignment:
Back-End must have
- Project is done in NodeJS
- Application API is functional and built with Swagger
- Has endponts for user, cart and products
- Has README.md, but unclear on running scripts
- Has scripts for running the project, but are invalid due to missing modules

Back-End should have
- Missing

Front-End must have
- Missing

Front-End should have
- Missing

Full Stack must have
- Missing


General notes:
- Project is completed. Code is well written and well documented.


Minor notes:
- When testing https://basic-shop-api.herokuapp.com/api-swagger-docs/#/ minor issues found are regarding api documentation, as follows:

POST /api/carts/v1/single
- Example Value | Schema missing:
{
  "id" : "60546cd36bb04b0015c635eb"
}

PUT /api/carts/v1/single
- Example Value | Schema missing:
{
  "id" : "60546cd36bb04b0015c635eb",
  "cart": [
    {
      "product": "6050f0215639da1ffcefad04",
      "count": 1
    },
    {
      "product": "6050f03e5639da1ffcefad05",
      "count": 2
    }
  ]
}

DELETE /api/carts/v1/single
- Example Value | Schema missing:
{
  "id" : "60546cd36bb04b0015c635eb"
}

GET /api/products/v1
- Missing (Admin Access) in description

PUT /api/products/v1
- Missing (Admin Access) in description
- Example Value | Schema missing:
{
  "id": "605473506bb04b0015c635f2",
  "name": "Nike shoes for kids",
  "price": 50,
  "quantity": 100
}

PUT /api/products/v1/remove
- visible=false is not required
- Missing (Admin Access) in description
- Example Value | Schema missing:
{
  "id": "605473506bb04b0015c635f2"
}
```

**Comment by nikicivan** [comment]
> Hello @nikicivan ,
> 
> Thank you for your submission.
> Below this you can find my review. In short, the project is very well done.
> I will send my feedback to HR.
> 
> Cheers,
> Nenad
> 
> ```
> Review for: nikicivan
> Completed on: 19.03.2021
> Assignment: https://github.com/polazak/assignments/blob/main/basic-shop.job-interview-assignment.md
> 
> 
> From assignment:
> Back-End must have
> - Project is done in NodeJS
> - Application API is functional and built with Swagger
> - Has endponts for user, cart and products
> - Has README.md, but unclear on running scripts
> - Has scripts for running the project, but are invalid due to missing modules
> 
> Back-End should have
> - Missing
> 
> Front-End must have
> - Missing
> 
> Front-End should have
> - Missing
> 
> Full Stack must have
> - Missing
> 
> 
> General notes:
> - Project is completed. Code is well written and well documented.
> 
> 
> Minor notes:
> - When testing https://basic-shop-api.herokuapp.com/api-swagger-docs/#/ minor issues found are regarding api documentation, as follows:
> 
> POST /api/carts/v1/single
> - Example Value | Schema missing:
> {
>   "id" : "60546cd36bb04b0015c635eb"
> }
> 
> PUT /api/carts/v1/single
> - Example Value | Schema missing:
> {
>   "id" : "60546cd36bb04b0015c635eb",
>   "cart": [
>     {
>       "product": "6050f0215639da1ffcefad04",
>       "count": 1
>     },
>     {
>       "product": "6050f03e5639da1ffcefad05",
>       "count": 2
>     }
>   ]
> }
> 
> DELETE /api/carts/v1/single
> - Example Value | Schema missing:
> {
>   "id" : "60546cd36bb04b0015c635eb"
> }
> 
> GET /api/products/v1
> - Missing (Admin Access) in description
> 
> PUT /api/products/v1
> - Missing (Admin Access) in description
> - Example Value | Schema missing:
> {
>   "id": "605473506bb04b0015c635f2",
>   "name": "Nike shoes for kids",
>   "price": 50,
>   "quantity": 100
> }
> 
> PUT /api/products/v1/remove
> - visible=false is not required
> - Missing (Admin Access) in description
> - Example Value | Schema missing:
> {
>   "id": "605473506bb04b0015c635f2"
> }
> ```

Hello @nenadpejic,

thanks for the review that you sent me. I'm available if anything else is needed.

Cheers,
Ivan.
